# About Dataset

**Context**

"Predict behavior to retain customers. You can analyze all relevant customer data and develop focused customer retention programs." [IBM Sample Data Sets]

**Content**

Each row represents a customer, each column contains customer’s attributes described on the column Metadata.

The data set includes information about:

- Customers who left within the last month – the column is called Churn
- Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
- Customer account information – how long they’ve been a customer, contract, payment method, paperless billing, monthly charges, and total charges
- Demographic info about customers – gender, age range, and if they have partners and dependents

# Load and Explore Data

In [72]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df = pd.read_csv(r"C:\Users\COMPUMARTS\Desktop\Telecom Churn Prediction\data\raw\Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [74]:
df.shape

(7043, 21)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [76]:
df.describe(include='all')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,7590-VHVEG,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

In [77]:
for col in df.columns:
    if df[col].dtype == object:
        num_unique = df[col].nunique() 

        if num_unique < 5:
            print(f'{col} ({num_unique} unique values): {df[col].unique()}')
        else:
            print(f'{col} has {num_unique} unique values (Too many to print).')
            
    else:
        print(f'{col} is Numerical.')

customerID has 7043 unique values (Too many to print).
gender (2 unique values): ['Female' 'Male']
SeniorCitizen is Numerical.
Partner (2 unique values): ['Yes' 'No']
Dependents (2 unique values): ['No' 'Yes']
tenure is Numerical.
PhoneService (2 unique values): ['No' 'Yes']
MultipleLines (3 unique values): ['No phone service' 'No' 'Yes']
InternetService (3 unique values): ['DSL' 'Fiber optic' 'No']
OnlineSecurity (3 unique values): ['No' 'Yes' 'No internet service']
OnlineBackup (3 unique values): ['Yes' 'No' 'No internet service']
DeviceProtection (3 unique values): ['No' 'Yes' 'No internet service']
TechSupport (3 unique values): ['No' 'Yes' 'No internet service']
StreamingTV (3 unique values): ['No' 'Yes' 'No internet service']
StreamingMovies (3 unique values): ['No' 'Yes' 'No internet service']
Contract (3 unique values): ['Month-to-month' 'One year' 'Two year']
PaperlessBilling (2 unique values): ['Yes' 'No']
PaymentMethod (4 unique values): ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges is Numerical.
TotalCharges has 6531 unique values (Too many to print).
Churn (2 unique values): ['No' 'Yes']

Based on exploration:
- There is a numeric variable currently stored as a string (object) type.
- Most categorical variables have 2, 3, or 4 unique categories.
- Variables with only 2 categories will be replaced by 0 and 1 (Binary Encoding).
- Variables with 3 or 4 categories will be transformed using One-Hot Encoding.

In [78]:
df.replace('No internet service','No',inplace=True)
df.replace('No phone service','No',inplace=True)

In [79]:
cols_to_check = ['MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in cols_to_check:
    print(f'{col}: {df[col].unique()}')

MultipleLines: ['No' 'Yes']
OnlineSecurity: ['No' 'Yes']
OnlineBackup: ['Yes' 'No']
DeviceProtection: ['No' 'Yes']
TechSupport: ['No' 'Yes']
StreamingTV: ['No' 'Yes']
StreamingMovies: ['No' 'Yes']

# Binary Encoding

In [ ]:
# Binary categorical columns (2 unique values)
binary_cols = ['gender', 'Partner' , 'Dependents', 'PhoneService' , 'PaperlessBilling',
                'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
                'TechSupport', 'StreamingTV', 'StreamingMovies' ,'Churn']

# Map Yes/No and Male/Female to 0/1
df[binary_cols] = df[binary_cols].replace({
    'Yes': 1 , 'No': 0,
    'Male': 1 , 'Female': 0
})

In [81]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,0,DSL,0,...,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,0,DSL,1,...,1,0,0,0,One year,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,1,0,0,0,2,1,0,DSL,1,...,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,0,DSL,1,...,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,Fiber optic,0,...,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   int64
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   int64
 4   Dependents        7043 non-null   int64
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   int64
 7   MultipleLines     7043 non-null   int64
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   int64
 10  OnlineBackup      7043 non-null   int64
 11  DeviceProtection  7043 non-null   int64
 12  TechSupport       7043 non-null   int64
 13  StreamingTV       7043 non-null   int64
 14  StreamingMovies   7043 non-null   int64
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   int64
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   int64
dtypes: float64(1), int64(15), object(5)
memory usage: 1.1+ MB

# One-Hot Encoding

In [ ]:
# Categorical columns with > 2 unique values
multi_cat_cols = ['InternetService','Contract','PaymentMethod']

# One-hot encode
df = pd.get_dummies(df , columns=multi_cat_cols , dtype=int , drop_first=True)

In [84]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,...,MonthlyCharges,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,0,1,0,1,0,0,0,1,...,29.85,29.85,0,0,0,0,0,0,1,0
1,5575-GNVDE,1,0,0,0,34,1,0,1,0,...,56.95,1889.5,0,0,0,1,0,0,0,1
2,3668-QPYBK,1,0,0,0,2,1,0,1,1,...,53.85,108.15,1,0,0,0,0,0,0,1
3,7795-CFOCW,1,0,0,0,45,0,0,1,0,...,42.30,1840.75,0,0,0,1,0,0,0,0
4,9237-HQITU,0,0,0,0,2,1,0,0,0,...,70.70,151.65,1,1,0,0,0,0,1,0

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 25 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   customerID                             7043 non-null   object
 1   gender                                 7043 non-null   int64
 2   SeniorCitizen                          7043 non-null   int64
 3   Partner                                7043 non-null   int64
 4   Dependents                             7043 non-null   int64
 5   tenure                                 7043 non-null   int64
 6   PhoneService                           7043 non-null   int64
 7   MultipleLines                          7043 non-null   int64
 8   OnlineSecurity                         7043 non-null   int64
 9   OnlineBackup                           7043 non-null   int64
 10  DeviceProtection                       7043 non-null   int64
 11  TechSupport                            7043 non-null   int64
 12  StreamingTV                            7043 non-null   int64
 13  StreamingMovies                        7043 non-null   int64
 14  PaperlessBilling                       7043 non-null   int64
 15  MonthlyCharges                         7043 non-null   float64
 16  TotalCharges                           7043 non-null   object
 17  Churn                                  7043 non-null   int64
 18  InternetService_Fiber optic            7043 non-null   int32
 19  InternetService_No                     7043 non-null   int32
 20  Contract_One year                      7043 non-null   int32
 21  Contract_Two year                      7043 non-null   int32
 22  PaymentMethod_Credit card (automatic)  7043 non-null   int32
 23  PaymentMethod_Electronic check         7043 non-null   int32
 24  PaymentMethod_Mailed check             7043 non-null   int32
dtypes: float64(1), int32(7), int64(15), object(2)
memory usage: 1.2+ MB

In [86]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges', 'TotalCharges',
       'Churn', 'InternetService_Fiber optic', 'InternetService_No',
       'Contract_One year', 'Contract_Two year',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

# Cleaning

In [87]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [88]:
df = df.drop('customerID' , axis=1)

In [90]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,MonthlyCharges,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,1,0,...,29.85,29.85,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,1,0,1,...,56.95,1889.50,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,0,1,1,0,...,53.85,108.15,1,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,1,0,1,...,42.30,1840.75,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,1,0,0,0,0,1,0

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int64
 1   SeniorCitizen                          7043 non-null   int64
 2   Partner                                7043 non-null   int64
 3   Dependents                             7043 non-null   int64
 4   tenure                                 7043 non-null   int64
 5   PhoneService                           7043 non-null   int64
 6   MultipleLines                          7043 non-null   int64
 7   OnlineSecurity                         7043 non-null   int64
 8   OnlineBackup                           7043 non-null   int64
 9   DeviceProtection                       7043 non-null   int64
 10  TechSupport                            7043 non-null   int64
 11  StreamingTV                            7043 non-null   int64
 12  StreamingMovies                        7043 non-null   int64
 13  PaperlessBilling                       7043 non-null   int64
 14  MonthlyCharges                         7043 non-null   float64
 15  TotalCharges                           7032 non-null   float64
 16  Churn                                  7043 non-null   int64
 17  InternetService_Fiber optic            7043 non-null   int32
 18  InternetService_No                     7043 non-null   int32
 19  Contract_One year                      7043 non-null   int32
 20  Contract_Two year                      7043 non-null   int32
 21  PaymentMethod_Credit card (automatic)  7043 non-null   int32
 22  PaymentMethod_Electronic check         7043 non-null   int32
 23  PaymentMethod_Mailed check             7043 non-null   int32
dtypes: float64(2), int32(7), int64(15)
memory usage: 1.1 MB